In [17]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn import tree
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

In [18]:
url = "predicting_cancer.csv"
#names = ['Variance', 'Skewness', 'Curtosis', 'Entropy', 'class']
train = pd.read_csv("predicting_cancer.csv")

In [19]:
train.head(20)

,CodeNumber,ClumpThickness,UniformityCellSize,UniformityCellShape,MarginalAdhesion,SingleEpithelialCellSize,BareNuclei,BlandChromatin,NormalNucleoli,Mitoses,CancerType
0,1000025,5,1,1,1,2,1,3,1,1,2
1,1002945,5,4,4,5,7,10,3,2,1,2
2,1015425,3,1,1,1,2,2,3,1,1,2
3,1016277,6,8,8,1,3,4,3,7,1,2
4,1017023,4,1,1,3,2,1,3,1,1,2
5,1017122,8,10,10,8,7,10,9,7,1,4
6,1018099,1,1,1,1,2,10,3,1,1,2
7,1018561,2,1,2,1,2,1,3,1,1,2
8,1033078,2,1,1,1,2,1,1,1,5,2
9,1033078,4,2,1,1,2,1,2,1,1,2
10,1035283,1,1,1,1,1,1,3,1,1,2
11,1036172,2,1,1,1,2,1,2,1,1,2
12,1041801,5,3,3,3,2,3,4,4,1,4
13,1043999,1,1,1,1,2,3,3,1,1,2
14,1044572,8,7,5,10,7,9,5,5,4,4
15,1047630,7,4,6,4,6,1,4,3,1,4
16,1048672,4,1,1,1,2,1,2,1,1,2
17,1049815,4,1,1,1,2,1,3,1,1,2
18,1050670,10,7,7,6,4,10,4,1,2,4
19,1050718,6,1,1,1,2,1,3,1,1,2

In [24]:
train=train[train['BareNuclei']!= '?']
x=train.drop('CancerType',axis=1)#x is i/p features as we drop the target col
y=train['CancerType']#y is o/p as here only the target col
validation_size = 0.20
seed = 7
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size=validation_size, random_state=seed)

In [27]:
clf = KNeighborsClassifier(n_neighbors=3,algorithm='brute',leaf_size=30,n_jobs=-1)
clf=clf.fit(X_train, Y_train)
predictions=(clf.predict(X_test))
predictions

array([2, 2, 2, 4, 2, 4, 2, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4,
       2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 4, 2, 2, 4, 2, 2, 2, 2, 2, 2, 4, 2,
       2, 2, 2, 4, 2, 2, 2, 2, 2, 4, 2, 2, 2, 4, 2, 2, 2, 4, 4, 2, 2, 2,
       2, 2, 4, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 4, 2, 2, 2,
       2, 2, 4, 4, 4, 4, 2, 2, 2, 2, 4, 4, 2, 2, 2, 4, 2, 4, 2, 2, 4, 4,
       2, 2, 2, 2, 4, 2, 4, 2, 4, 2, 4, 2, 2, 4, 2, 2, 2, 2, 4, 2, 2, 2,
       2, 2, 4, 2, 4], dtype=int64)

In [28]:
from sklearn.metrics import accuracy_score , confusion_matrix , classification_report
print(accuracy_score(Y_test,predictions))

0.6496350364963503